### ISSUE TITLE
please support passing in a `Publisher<T>` to the `assemble` method instead of a synchronous `Iterable<T>`.

### ISSUE THREAD

**Issue by joshlong** [pellse/assembler#11]
I would like to use Assembler to stream the results and aggregate the details as the results are returning.

**Comment by pellse** [comment]
Linking to #10 as this issue seems to be closely related. Thanks a lot Josh for the feedback, the issue you raised is interpreted as a strong indication that there is an actual demand for this particular feature and the assembler library as a whole, so this will be put at the top of the priority list

**Comment by pellse** [comment]
I want to make sure that got this feature request right, currently the library supports processing of reactive streams in a non-blocking way (minus issue #10 ), possibly infinite stream, here is an example https://github.com/pellse/assembler#flux
```java
Flux<Transaction> transactionFlux = getCustomerFlux()  // something that returns a Flux<Customer>
    .bufferTimeout(10, ofSeconds(5)) // every 5 seconds or max of 10 customers, returns Flux<List<Customer>>
    .flatMap(assembler::assemble) // flatMap(customerList -> assembler.assemble(customerList)))
```
Another scenario (not your use case though from my understanding) could be to fully drain the Flux (when we know in advance it's a finite stream e.g. a list of parameters passed as a Flux in a REST call handled by Spring WebFlux)
```java
Flux<Transaction> toTransaction(@RequestBody Flux<Customer> customerFlux) {
    return customerFlux
        .collectList()
        .flatMapMany(assembler::assemble)
}
```
By design, the `assemble` method needs to consume every element from the upstream (or batches of elements from the upstream) to retrieve in one shot all the correlation ids (or primary keys) needed to be used by downstream sub-query requests (those not being fully reactive yet, see #10 ) to allow a single call per sub-query passing the full list of ids (vs. one call per id) i.e. batching (or buffering) the aggregation process instead of doing it on a per element basis to avoid the N + 1 query problem. The management/configuration of those batches was deliberately left outside of the Assembler as shown in the code snippet above, using an `Iterable<T>` here was to make it explicit that this is a finite list, while keeping the reactive behavior when used within a scenario where we reactively split a stream into chunks (using `Flux.bufferXXX` methods)

Passing a `Publisher<T>` to the `assembler` method could be done, but in the scenario where the `Publisher<T>` is an infinite stream, the Assembler library would have to internally handle the buffering to limit the number of elements to read from the upstream before collecting ids from those elements to trigger sub-query calls on downstreams.

Let me know if this covers the use case you had in mind (issue #10 would still need to be implemented though, independently of this ticket). The other option I see is that you might have meant using the Assembler to process/aggregate on a per element basis (no buffering) i.e. not something to be used as a solution to the N + 1 query problem, but more of a nice layer on top of the reactive stream combiner operators (e.g. `Flux.zip`, `Flux.combineLatest`, etc.). If that is the case, this is anyway something I was considering doing at some point, pass a `Publisher<T>` to the `assemble` method no matter what, but have a way to pass a config to specify if each element of the stream represented by that `Publisher<T>` should be handled on a per element basis or if the entire stream of elements from the `Publisher` should be consumed to implement batching of sub-queries.

**Comment by pellse** [comment]
Your great suggestion is now implemented, the internal logic of the Assembler was rewritten with Project Reactor, the details are on the main page of the project https://github.com/pellse/assembler. Replacing assembler-flux dependency with reactive-assembler-core dependency in Java/Kotlin projects will allow passing in a `Publisher<T>` everywhere
