### ISSUE TITLE
[Question] One to many unit test

### ISSUE THREAD

**Issue by whisper-bye** [pellse/assembler#22]
sorry to ask here, I don't know how to create a order record
and could not found the rule static method

```
dependencies {
	implementation 'io.github.pellse:assembler-core:0.5.0'
	implementation 'io.github.pellse:assembler-util:0.5.0'
}
```

```java
record Order(int id, List<OrderItem> orderItems) {}
record OrderItem(int id, int orderId, Product product) {}
record Product(int id) {}

CompletableFuture<Order> order = assemblerOf(Order.class)
    // ... ???
```

**Comment by pellse** [comment]
My apologies for missing your question (and for the late reply), here is where the unit tests are for the `CompletableFuture `implementation:

https://github.com/pellse/assembler/blob/main/assembler-core/src/test/java/io/github/pellse/assembler/future/CompletableFutureAssemblerTest.java

Note that although the process of aggregating different sources of data (via rules) is asynchronous, the data sources themselves cannot be async. For example, `getAllOrders()` has to return a List (or a `Collection` if using the more generic `oneToMany()` function) vs. `CompletableFuture<List<OrderItem>> getAllOrders()`:

```java
List<OrderItem> getAllOrders(List<Long> customerIds);

CompletableFuture<List<Transaction>> transactions = assemblerOf(Transaction.class)
                .withIdExtractor(Customer::customerId)
                .withAssemblerRules(
                        oneToOne(AssemblerTestUtils::getBillingInfo, BillingInfo::customerId, BillingInfo::new),
                        oneToManyAsList(AssemblerTestUtils::getAllOrders, OrderItem::customerId),
                        Transaction::new)
                .using(completableFutureAdapter())
                .assembleFromSupplier(this::getCustomers);
```

The current reactive implementation (https://search.maven.org/artifact/io.github.pellse/reactive-assembler-core/0.5.0/jar) fix that limitation if this is something you might need and if you don't mind having a dependency on [Project Reactor](https://projectreactor.io/). I mention it because the active development is focused on the reactive implementation. A new release 0.5.1 is also coming in a few days.

**Comment by whisper-bye** [comment]
thanks for your reply
